### ISSUE TITLE
Species and genus weight

### ISSUE THREAD

**Issue by oschakoory** [MicrobeLab/DeepMicrobes-data#2]
DeepMicrobes is very interesting. I am training DeepMicrobes on another set of genomes and i wanted to know how do you calculate weight for species and genus? is it from the fasta file?

**Comment by MicrobeLab** [comment]
Sorry I do not understand what is "calculate weight for species and genus". Model weights are obtained during training. The scripts we provide can take fasta file as input.

**Comment by oschakoory** [comment]
To train the NN, i need to provide weight (species/genus) directory.

To train a DNN model for DeepMicrobes:

DeepMicrobes.py --input_tfrec=train.tfrec --model_name=attention --model_dir=/path/to/weights

My question is how do we get these weights before training? 

You have provided trained weight for genus and species. But since i am using my own data to train the NN, i cannot use your weights. 

I did all the steps before but none provided me with weights. So how can i get the trained weight as input to DeepMicrobes.py?

Thank you.

**Comment by MicrobeLab** [comment]
When you start training, the weights will be randomly initialized. You do not need to provide them before training. The script will output the trained weights as checkpoints during training. Remember to make sure whether the script was in the mode of training or making predictions. Thanks.
